# Generated by Django 3.2.25 on 2024-05-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
    ]
